# Generated by Django 4.0.4 on 2022-05-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('libelle', models.CharField(blank=True, max_length=100)),
                ('prix_achat', models.IntegerField(blank=True)),
                ('date_create', models.DateTimeField(blank=True)),
                ('date_peremtion', models.DateTimeField(blank=True)),
            ],
        ),
    ]
